version: '2'
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 127.0.0.1:80:80
      - 4201:4201
    networks:
      - esnet
    tty: true
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - '127.0.0.1:3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql:delegated
    container_name: mysql-local
    networks:
      - esnet
  redis:
    restart: always
    image: redis
    container_name: cache
    command: redis-server --requirepass dNfu3eQZEllBm8bnp0GSiqPegUWVAkOH
    ports:
      - '6379:6379'
    expose:
      - 6379
    networks:
      - esnet
networks:
  esnet:
